# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllContentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=30)),
                ('pubulish_date', models.DateField()),
                ('series', models.IntegerField()),
                ('page', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LevelDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('image_url', models.CharField(max_length=30)),
                ('pubulish_date', models.DateField()),
                ('series', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('image_url', models.CharField(max_length=30)),
                ('pubulish_date', models.DateField()),
                ('page', models.IntegerField()),
                ('series_name', models.TextField()),
                ('series', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
